export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const LOAD_MEMBERS_SUCCESS = "LOAD_MEMBERS_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
