export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const LOAD_MEMBERS_SUCCESS = "LOAD_MEMBERS_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";

// action types for keeping track of API status
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_MEMBER_OPTIMISTIC = "DELETE_MEMBER_OPTIMISTIC";
